session: beatmap-server

root: ~/datenshi/proxybm

windows:
  - name: beatmap-server
    layout: tiled
    commands:
      - python3.6 aoba-proxy.py
    panes:
      - type: horizontal
        commands: []
