session: bot-irc

root: ~/datenshi/yohane-irc

stop:
  - tmux send-keys -t bot-irc.0 "C-c" ENTER

windows:
  - name: bot-irc
    layout: tiled
    commands:
      - sleep 10
      - ./matterbridge
    panes:
      - type: horizontal
        commands: []
