session: exhentai

root: ~/exhentai-db

windows:
  - name: exhentai
    layout: main-horizontal
    commands:
      - npm start
    panes:
      - type: horizontal
        commands:
          - ./rerun '08:37'
