session: ip-backend

root: ~/datenshi/gopi

stop:
  - tmux send-keys -t ip-backend.0 "C-c" ENTER

windows:
  - name: ip-backend
    layout: tiled
    commands:
      - ./gopi
    panes:
      - type: horizontal
        commands: []
