session: ip-backend

root: ~/datenshi/gopi

windows:
  - name: ip-backend
    layout: main-horizontal
    commands:
      - ./gopi
    panes:
      - type: horizontal
        commands:
          - clear
