session: multi-backend

root: ~/datenshi/multi/vinse-backend

stop:
  - tmux send-keys -t multi-backend.0 "C-c" ENTER

windows:
  - name: multi-backend
    layout: tiled
    commands:
      - ./vinse-backend
    panes:
      - type: horizontal
        commands: []
