rebalance_panes_after: 5
session: nadeko
windows:
- commands:
  - dotnet run -c Release -p src/NadekoBot/NadekoBot.csproj
  layout: tiled
  name: nadeko-hq
  panes:
  - commands: []
  - commands: []
  - commands: []
  root: /root/NadekoBot
