session: network

windows:
  - name: network
    layout: tiled
    commands:
      - iftop
    panes:
      - type: horizontal
        commands:
          - htop
      - type: vertical
        commands: []
