session: network

windows:
  - name: network
    layout: main-horizontal
    commands:
      - iftop
    panes:
      - type: horizontal
        commands:
          - htop
      - type: vertical
        commands:
          - clear
