rebalance_panes_after: 5
root: /root/datenshi/pep.py
session: peppy
windows:
- commands:
  - python3.6 pep.py
  layout: tiled
  name: peppy
  panes:
  - commands: []
  - commands: []
  - commands: []
- layout: 67c4,224x58,0,0,72
  name: bash
  panes: []
  root: /var/lib/mysql
