session: web

root: ~/datenshi/hanayo

stop:
  - tmux send-keys -t web.0 "C-c" ENTER

windows:
  - name: web
    layout: tiled
    commands:
      - ./hanayo
    panes:
      - type: horizontal
        commands: []
