session: yohane-irc

root: ~/datenshi/yohane-irc

windows:
  - name: yohane-irc
    layout: main-horizontal
    commands:
      - ./matterbridge
    panes:
      - type: horizontal
        commands:
          - clear
