session: yohane-irc

root: ~/datenshi/yohane-irc

stop:
  - tmux send-keys -t yohane-irc.0 "C-c" ENTER

windows:
  - name: yohane-irc
    layout: tiled
    commands:
      - ./matterbridge
    panes:
      - type: horizontal
        commands: []
